/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.*;

import ghost.objects.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test
    void playerTest() {
        // Ensure that the player field in App is not null
        App app = new App();
        app.setPlayer(500, 400, 1, 3);
        assertNotNull(app.player);
    }

    @Test
    void ghostsTest() {
        // Ensure that the ghosts are not null, and they are all in GameMap.ghosts.
        App app = new App();
        app.setAmbusher(500, 400, 1);
        assertNotNull(app.ambusher);
        app.setChaser(400, 300, 1);
        assertNotNull(app.chaser);
        app.setWhim(300, 200, 1);
        assertNotNull(app.whim);
        app.setIgnorant(200, 100, 1);
        assertNotNull(app.ignorant);
        assertFalse(GameMap.ghosts.isEmpty());
    }

    @Test
    void mapTest() {
        // Ensure that the map field is not null
        App app = new App();
        app.map = new GameMap();
        assertNotNull(app.map);
    }
}
